server:
  port: 0



proxy:
  items:
    - port: 808
      proxy:
        proxyType: SOCKS5
        host: 127.0.0.1
        port: 1080



logging:
  level:
    org.springframework.web: ERROR
    io.netty.handler.logging: DEBUG